
name: Send Email Reminders

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours (at 00:00 and 12:00 UTC)
  workflow_dispatch:        # Allows manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or whatever you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo python-dotenv

      - name: Run the script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: |
          python main.py
